### ISSUE TITLE
accessibility fixes

### ISSUE THREAD

**Issue by kenirwin** [kenirwin/FacetFilter#38]
- [x] add a named region on the filter section (and maybe also on the main section?)
- [x] add a role=alert +assertive on the div that reports the number of search results upon filtering; these should happen on page load
- [x] add aria-labels for "page 1", "next page", etc on the pagination controls
- [x] add aria-current and related controls on the pagination links instead of on the `<li>` 
- [x] date slider may need some labels to differentiate between the lower-bound value and the upper-bound value

**Comment by 23jaredbarrett** [comment]
1. For the issue "focus order" this is controlled simply where the user places the div with id="facets" in the DOM. For example, in "faces.html", we can simply move the div to be focusable first by moving it before #main-panel, and the code will compile fine. However, it is visibly shown on the left side after the change (which typically makes sense because it matches the reading order).

**Comment by kenirwin** [comment]
Deleted item: date slider should have min/max values that reflect the date ranges (e.g. "1940s") rather than than the position number (e.g. "3.0")

The aria-valuetext that we're using is the appropriate value: 'The `aria-valuetext` attribute is used with the `aria-valuenow` attribute, not instead of it, unless that value is not known. `aria-valuetext` is only needed when the numeric value of `aria-valuenow` is not meaningful."[MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuetext)
